using NUnit.Framework;

namespace CSharpDepsGraph.Tests.Integrations;

public class GeneratedCodeTests : BaseIntegrationsTests
{
    [Test]
    public void AssemblyInfoIgnored()
    {
        var graph1 = GetGraph();

        Assert.That(graph1.GetNodes(AsmName.Netstandard, "System/Runtime/Versioning/TargetFrameworkAttribute"), Is.Empty);
        Assert.That(graph1.GetNodes(AsmName.Netstandard, "System/Reflection/AssemblyCompanyAttribute"), Is.Empty);

        var graph2 = GetGraph(o => o.ParseGeneratedCode = true);

        Assert.That(graph2.GetNodes(AsmName.Netstandard, "System/Runtime/Versioning/TargetFrameworkAttribute"), Is.Empty);
        Assert.That(graph2.GetNodes(AsmName.Netstandard, "System/Reflection/AssemblyCompanyAttribute"), Is.Empty);
    }

    [Test]
    public void AutoGeneratedComment()
    {
        var graph1 = GetGraph();
        var node1 = graph1.GetNode(AsmName.TestProjectCli, "TestProject/Cli/GenComment");
        var methodNode1 = node1.GetNode("PublicMethod()");

        Assert.That(IsGenerated(node1));
        Assert.That(IsGenerated(methodNode1));

        Assert.That(node1.Childs.Count(), Is.EqualTo(1));
        Assert.That(graph1.GetOutgoingLinks(methodNode1).Length, Is.Zero);

        var graph2 = GetGraph(o => o.ParseGeneratedCode = true);
        var node2 = graph2.GetNode(AsmName.TestProjectCli, "TestProject/Cli/GenComment");
        var methodNode21 = node2.GetNode("PublicMethod()");
        var methodNode22 = node2.GetNode("PrivateMethod()");
        var methodNode21Links = graph2.GetOutgoingLinks(methodNode21);

        Assert.That(IsGenerated(node2));
        Assert.That(IsGenerated(methodNode21));
        Assert.That(IsGenerated(methodNode22));

        Assert.That(node2.Childs.Count(), Is.EqualTo(2));
        Assert.That(methodNode21Links.Length, Is.EqualTo(1));
        Assert.That(methodNode21Links[0].Target.Uid, Is.EqualTo(methodNode22.Uid));
    }

    [Test]
    public void EmittedSourceGenerators()
    {
        var graph1 = GetGraph();
        var node1 = graph1.GetNode(AsmName.TestProjectCli, "TestProject/Generated/Foo");
        var methodNode1 = node1.GetNode("PublicMethod()");

        Assert.That(IsGenerated(node1));
        Assert.That(IsGenerated(methodNode1));
        Assert.That(node1.Childs.Count(), Is.EqualTo(1));
        Assert.That(graph1.GetOutgoingLinks(methodNode1).Length, Is.Zero);

        var graph2 = GetGraph(o => o.ParseGeneratedCode = true);
        var node2 = graph2.GetNode(AsmName.TestProjectCli, "TestProject/Generated/Foo");
        var methodNode21 = node2.GetNode("PublicMethod()");
        var methodNode22 = node2.GetNode("PrivateMethod()");
        var methodNode21Links = graph2.GetOutgoingLinks(methodNode21);

        Assert.That(IsGenerated(node2));
        Assert.That(IsGenerated(methodNode21));
        Assert.That(IsGenerated(methodNode22));

        Assert.That(node2.Childs.Count(), Is.EqualTo(2));
        Assert.That(methodNode21Links.Length, Is.EqualTo(1));
        Assert.That(methodNode21Links[0].Target.Uid, Is.EqualTo(methodNode22.Uid));
    }

    [Test]
    public void PlainSourceGenerators()
    {
        var graph = GetGraph();

        Assert.That(!IsGenerated(graph.GetNode(AsmName.TestProject, "TestProject/Generated/GeneratedClassPartial")));
        Assert.That(!IsGenerated(graph.GetNode(AsmName.TestProject, "TestProject/Generated/GeneratedClassPartial/PartialMethod()")));
        Assert.That(IsGenerated(graph.GetNode(AsmName.TestProject, "TestProject/Generated/GeneratedClassPartial/GeneratedMethod()")));

        Assert.That(IsGenerated(graph.GetNode(AsmName.TestProject, "TestProject/Generated/GeneratedClass")));
        Assert.That(IsGenerated(graph.GetNode(AsmName.TestProject, "TestProject/Generated/GeneratedClass/GeneratedMethod()")));
    }

    public static bool IsGenerated(INode node)
    {
        return node.SyntaxLinks.All(sl => sl.LocationKind == LocationKind.Generated);
    }
}