// ------------------------------------------------------------------------------
// <auto-generated>
//    Fake auto gen
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TestProject.Cli;

public class GenComment
{
    public void PublicMethod()
    {
        PrivateMethod();
    }

    private void PrivateMethod()
    {
        var a = 0;
    }
}