using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Shared.Extensions;

namespace CSharpDepsGraph.Building.Services;

internal class GeneratedCodeDetector
{
    private static readonly string[] _autoGeneratedStrings = new[] {
        "<autogenerated",
        "<auto-generated"
        };

    private readonly Project _project;
    private readonly Dictionary<string, GeneratedFileKind> _resultCache;
    private readonly string? _baseIntermediateOutputPath;

    private HashSet<string>? _sourceGeneratedDocuments;

    public GeneratedCodeDetector(Project project)
    {
        _project = project;
        _baseIntermediateOutputPath = null; // todo

        /* todo get BaseIntermediateOutputPath
        var globalOptions = project.AnalyzerOptions.AnalyzerConfigOptionsProvider.GlobalOptions;
        var opts = globalOptions.Keys
            .Select(k =>
            {
                return (k, globalOptions.TryGetValue(k, out var value) ? value : null);
            });
        */

        _resultCache = new();
    }

    public ValueTask<GeneratedFileKind> GetGeneratedFileKindAsync(SyntaxTree syntaxTree, CancellationToken cancellationToken)
    {
        if (_resultCache.TryGetValue(syntaxTree.FilePath, out var result))
        {
            return ValueTask.FromResult(result);
        }

        if (IsGeneratedDocument(syntaxTree, cancellationToken))
        {
            return ValueTask.FromResult(AppendPath(syntaxTree.FilePath, true));
        }

        return CheckSourceGenerators(syntaxTree, cancellationToken);
    }

    private async ValueTask<GeneratedFileKind> CheckSourceGenerators(
        SyntaxTree syntaxTree,
        CancellationToken cancellationToken
        )
    {
        if (_sourceGeneratedDocuments is null)
        {
            var documents = await _project.GetSourceGeneratedDocumentsAsync(cancellationToken);

            _sourceGeneratedDocuments = documents
                .Where(doc => doc.FilePath != null)
                .Select(doc => doc.FilePath ?? "")
                .ToHashSet();
        }

        var path = syntaxTree.FilePath;
        var isGenerated = _sourceGeneratedDocuments.Contains(path);

        return AppendPath(path, isGenerated);
    }

    private GeneratedFileKind AppendPath(string path, bool isGenerated)
    {
        var result = isGenerated ? GeneratedFileKind.Hiden : GeneratedFileKind.None;
        _resultCache.TryAdd(path, result);

        return result;
    }

    // Base on Roslyn.Utilities.GeneratedCodeUtilities
    private static bool IsGeneratedDocument(
        SyntaxTree tree,
        CancellationToken cancellationToken
        )
    {
        return IsGeneratedCodeFile(tree.FilePath)
            || BeginsWithAutoGeneratedComment(tree, cancellationToken);
    }

    private static bool IsGeneratedCodeFile(string? filePath)
    {
        if (!string.IsNullOrEmpty(filePath))
        {
            var fileName = Path.GetFileName(filePath);
            if (fileName.StartsWith("TemporaryGeneratedFile_", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }

            var extension = Path.GetExtension(fileName);
            if (!string.IsNullOrEmpty(extension))
            {
                var fileNameWithoutExtension = Path.GetFileNameWithoutExtension(filePath);
                if (fileNameWithoutExtension.EndsWith(".designer", StringComparison.OrdinalIgnoreCase) ||
                    fileNameWithoutExtension.EndsWith(".generated", StringComparison.OrdinalIgnoreCase) ||
                    fileNameWithoutExtension.EndsWith(".g", StringComparison.OrdinalIgnoreCase) ||
                    fileNameWithoutExtension.EndsWith(".g.i", StringComparison.OrdinalIgnoreCase))
                {
                    return true;
                }
            }
        }

        return false;
    }

    private static bool BeginsWithAutoGeneratedComment(
        SyntaxTree tree,
        CancellationToken cancellationToken
        )
    {
        var root = tree.GetRoot(cancellationToken);
        if (root.HasLeadingTrivia)
        {
            var leadingTrivia = root.GetLeadingTrivia();

            foreach (var trivia in leadingTrivia)
            {
                if (!trivia.IsKind(SyntaxKind.SingleLineCommentTrivia)
                    && trivia.IsKind(SyntaxKind.MultiLineCommentTrivia))
                {
                    continue;
                }

                var text = trivia.ToString();

                // Check to see if the text of the comment contains an auto generated comment.
                foreach (var autoGenerated in _autoGeneratedStrings)
                {
                    if (text.Contains(autoGenerated, StringComparison.InvariantCulture))
                    {
                        return true;
                    }
                }
            }
        }

        return false;
    }
}