using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Shared.Extensions;

namespace CSharpDepsGraph.Building.Services;

internal class GeneratedCodeDetector
{
    private static readonly string[] _autoGeneratedStrings = new[] {
        "<autogenerated",
        "<auto-generated"
        };

    private readonly List<string> _objPaths;
    private readonly HashSet<string> _sourceGeneratedDocuments;
    private readonly Dictionary<string, GeneratedFileKind> _resultCache;
    private readonly GraphBuildOptions _options;

    public GeneratedCodeDetector(GraphBuildOptions options)
    {
        _options = options;

        _objPaths = new();
        _resultCache = new();
        _sourceGeneratedDocuments = new();
    }

    public async Task PrepareProjectAsync(Project project, CancellationToken cancellationToken)
    {
        var objPath = DetectObjPath(project);
        if (objPath is not null)
        {
            _objPaths.Add(objPath);
        }

        var documents = await project.GetSourceGeneratedDocumentsAsync(cancellationToken);
        foreach (var document in documents)
        {
            _sourceGeneratedDocuments.Add(document.FilePath ?? "");
        }
    }

    public GeneratedFileKind GetGeneratedFileKindAsync(SyntaxTree syntaxTree, CancellationToken cancellationToken)
    {
        if (_resultCache.TryGetValue(syntaxTree.FilePath, out var result))
        {
            return result;
        }

        if (IsGeneratedDocument(syntaxTree, cancellationToken))
        {
            return AppendPath(syntaxTree.FilePath, true);
        }

        return CheckSourceGenerators(syntaxTree);
    }

    private GeneratedFileKind CheckSourceGenerators(SyntaxTree syntaxTree)
    {
        var path = syntaxTree.FilePath;
        var isGenerated = _sourceGeneratedDocuments.Contains(path);

        return AppendPath(path, isGenerated);
    }

    private GeneratedFileKind AppendPath(string path, bool isGenerated)
    {
        var result = GeneratedFileKind.None;
        if (isGenerated)
        {
            var inObjDir = _objPaths.Any(op => path.StartsWith(op, StringComparison.Ordinal));
            result = inObjDir || !_options.ParseVisibleGeneratedCode
                ? GeneratedFileKind.Hiden
                : GeneratedFileKind.Visible;
        }

        _resultCache.TryAdd(path, result);

        return result;
    }

    private static string? DetectObjPath(Project project)
    {
        /* todo get BaseIntermediateOutputPath
        var globalOptions = project.AnalyzerOptions.AnalyzerConfigOptionsProvider.GlobalOptions;
        var opts = globalOptions.Keys
            .Select(k =>
            {
                return (k, globalOptions.TryGetValue(k, out var value) ? value : null);
            });
        */

        var asmAttrsDoc = project.Documents.SingleOrDefault(
            d => d.FilePath?.EndsWith("AssemblyAttributes.cs", StringComparison.Ordinal) == true
        );

        return Path.GetDirectoryName(asmAttrsDoc?.FilePath);
    }

    // Based on Roslyn.Utilities.GeneratedCodeUtilities
    private static bool IsGeneratedDocument(
        SyntaxTree tree,
        CancellationToken cancellationToken
        )
    {
        return IsGeneratedCodeFile(tree.FilePath)
            || BeginsWithAutoGeneratedComment(tree, cancellationToken);
    }

    private static bool IsGeneratedCodeFile(string? filePath)
    {
        if (!string.IsNullOrEmpty(filePath))
        {
            var fileName = Path.GetFileName(filePath);
            if (fileName.StartsWith("TemporaryGeneratedFile_", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }

            var extension = Path.GetExtension(fileName);
            if (!string.IsNullOrEmpty(extension))
            {
                var fileNameWithoutExtension = Path.GetFileNameWithoutExtension(filePath);
                if (fileNameWithoutExtension.EndsWith(".designer", StringComparison.OrdinalIgnoreCase) ||
                    fileNameWithoutExtension.EndsWith(".generated", StringComparison.OrdinalIgnoreCase) ||
                    fileNameWithoutExtension.EndsWith(".g", StringComparison.OrdinalIgnoreCase) ||
                    fileNameWithoutExtension.EndsWith(".g.i", StringComparison.OrdinalIgnoreCase))
                {
                    return true;
                }
            }
        }

        return false;
    }

    private static bool BeginsWithAutoGeneratedComment(
        SyntaxTree tree,
        CancellationToken cancellationToken
        )
    {
        var root = tree.GetRoot(cancellationToken);
        if (root.HasLeadingTrivia)
        {
            var leadingTrivia = root.GetLeadingTrivia();

            foreach (var trivia in leadingTrivia)
            {
                if (!trivia.IsKind(SyntaxKind.SingleLineCommentTrivia)
                    && trivia.IsKind(SyntaxKind.MultiLineCommentTrivia))
                {
                    continue;
                }

                var text = trivia.ToString();

                // Check to see if the text of the comment contains an auto generated comment.
                foreach (var autoGenerated in _autoGeneratedStrings)
                {
                    if (text.Contains(autoGenerated, StringComparison.InvariantCulture))
                    {
                        return true;
                    }
                }
            }
        }

        return false;
    }
}