using NUnit.Framework;
using System.Linq;

namespace CSharpDepsGraph.Tests.Intergations;

public class GeneratedCodeTests : BaseIntergationsTests
{
    [Test]
    public void AssemblyInfoIgnored()
    {
        var graph = GetGraph();

        Assert.That(graph.GetNodes(AsmName.Netstandard, "System/Runtime/Versioning/TargetFrameworkAttribute"), Is.Empty);
        Assert.That(graph.GetNodes(AsmName.Netstandard, "System/Reflection/AssemblyCompanyAttribute"), Is.Empty);

        // todo check GraphBuildingOptions.ParseVisibleGeneratedCode
    }

    [Test]
    public void AutoGeneratedCommentIgnored()
    {
        var graph = GetGraph();
        var node = graph.GetNode("TestProject.Cli", "TestProject/Cli/GenComment");
        var methodNode = node.GetNode("PublicMethod()");

        Assert.That(node.Childs.Count(), Is.EqualTo(1));
        Assert.That(graph.GetOutgoingLinks(methodNode).Length, Is.Zero);
        Assert.That(IsGenerated(node));
        Assert.That(IsGenerated(methodNode));

        // todo check GraphBuildingOptions.ParseVisibleGeneratedCode
    }

    [Test]
    public void EmitedFileIgnored()
    {
        var graph = GetGraph();
        var node = graph.GetNode("TestProject.Cli", "TestProject/Generated/Foo");
        var methodNode = node.GetNode("PublicMethod()");

        Assert.That(node.Childs.Count(), Is.EqualTo(1));
        Assert.That(graph.GetOutgoingLinks(methodNode).Length, Is.Zero);
        Assert.That(IsGenerated(node));
        Assert.That(IsGenerated(methodNode));

        // todo check GraphBuildingOptions.ParseVisibleGeneratedCode
    }

    [Test]
    public void GeneratedDetect()
    {
        var graph = GetGraph();

        Assert.That(!IsGenerated(graph.GetNode(AsmName.TestProject, "TestProject/Generated/GeneratedClassPartial")));
        Assert.That(!IsGenerated(graph.GetNode(AsmName.TestProject, "TestProject/Generated/GeneratedClassPartial/PartialMethod()")));
        Assert.That(IsGenerated(graph.GetNode(AsmName.TestProject, "TestProject/Generated/GeneratedClassPartial/GeneratedMethod()")));

        Assert.That(IsGenerated(graph.GetNode(AsmName.TestProject, "TestProject/Generated/GeneratedClass")));
        Assert.That(IsGenerated(graph.GetNode(AsmName.TestProject, "TestProject/Generated/GeneratedClass/GeneratedMethod()")));
    }

    public static bool IsGenerated(INode node)
    {
        return node.SyntaxLinks.All(sl => sl.LocationKind == LocationKind.Generated);
    }
}