name: Check

on:
  push:
    branches: [ main, main-dev ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    name: Check ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [
          ubuntu-latest
          #windows-latest todo
          #macos-latest todo
        ]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build